[2022-09-05 03:08:00,497] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task 2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05 03:08:00,585] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task 2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05 03:08:00,586] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:08:00,587] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2022-09-05 03:08:00,588] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:08:00,703] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-09-01T00:00:00+00:00
[2022-09-05 03:08:00,708] {standard_task_runner.py:52} INFO - Started process 498 to run task
[2022-09-05 03:08:00,730] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v2', 'second_task', '2022-09-01T00:00:00+00:00', '--job-id', '107', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpl264t2_a', '--error-file', '/tmp/tmphr09nfz4']
[2022-09-05 03:08:00,736] {standard_task_runner.py:77} INFO - Job 107: Subtask second_task
[2022-09-05 03:08:00,963] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v2.second_task 2022-09-01T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 03:08:01,229] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v2
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-09-05 03:08:01,230] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-09-05 03:08:01,231] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2022-09-05 03:08:01,243] {bash.py:169} INFO - Output:
[2022-09-05 03:08:01,246] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2022-09-05 03:08:01,247] {bash.py:177} INFO - Command exited with return code 0
[2022-09-05 03:08:01,474] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, execution_date=20220901T000000, start_date=20220905T030800, end_date=20220905T030801
[2022-09-05 03:08:01,647] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 03:08:01,691] {local_task_job.py:146} INFO - Task exited with return code 0
