[2022-09-05 03:07:45,263] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task 2022-08-18T00:00:00+00:00 [queued]>
[2022-09-05 03:07:45,388] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task 2022-08-18T00:00:00+00:00 [queued]>
[2022-09-05 03:07:45,389] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:07:45,389] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2022-09-05 03:07:45,390] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:07:45,467] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-08-18T00:00:00+00:00
[2022-09-05 03:07:45,504] {standard_task_runner.py:52} INFO - Started process 371 to run task
[2022-09-05 03:07:45,524] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v2', 'second_task', '2022-08-18T00:00:00+00:00', '--job-id', '65', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp2xnx445z', '--error-file', '/tmp/tmpgyemlofh']
[2022-09-05 03:07:45,528] {standard_task_runner.py:77} INFO - Job 65: Subtask second_task
[2022-09-05 03:07:45,799] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v2.second_task 2022-08-18T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 03:07:46,005] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v2
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-18T00:00:00+00:00
[2022-09-05 03:07:46,006] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-09-05 03:07:46,007] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2022-09-05 03:07:46,045] {bash.py:169} INFO - Output:
[2022-09-05 03:07:46,054] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2022-09-05 03:07:46,060] {bash.py:177} INFO - Command exited with return code 0
[2022-09-05 03:07:46,246] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, execution_date=20220818T000000, start_date=20220905T030745, end_date=20220905T030746
[2022-09-05 03:07:46,502] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 03:07:46,545] {local_task_job.py:146} INFO - Task exited with return code 0
