[2022-09-05 11:47:17,776] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.insert_dim_date 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 11:47:17,829] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.insert_dim_date 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 11:47:17,830] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 11:47:17,830] {taskinstance.py:1043} INFO - Starting attempt 2 of 3
[2022-09-05 11:47:17,831] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 11:47:17,871] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): insert_dim_date> on 2022-09-04T00:00:00+00:00
[2022-09-05 11:47:17,879] {standard_task_runner.py:52} INFO - Started process 11086 to run task
[2022-09-05 11:47:17,884] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'insert_dim_date', '2022-09-04T00:00:00+00:00', '--job-id', '171', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpdia4vlez', '--error-file', '/tmp/tmphu839y25']
[2022-09-05 11:47:17,889] {standard_task_runner.py:77} INFO - Job 171: Subtask insert_dim_date
[2022-09-05 11:47:18,016] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.insert_dim_date 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 11:47:18,087] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=insert_dim_date
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 11:47:18,102] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:47:18,132] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:47:18,156] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:47:18,215] {taskinstance.py:1455} ERROR - invalid input syntax for type integer: "2020-02-25"
LINE 1: ...ate,month,quater_of_year,year,is_weekend) VALUES ('2020-02-2...
                                                             ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/dim_date.py", line 9, in main_date
    insert_dwh_table(df)
  File "/opt/airflow/dags/usecase/dim_date.py", line 82, in insert_dwh_table
    cursor.execute(sql, tuple(row))
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "2020-02-25"
LINE 1: ...ate,month,quater_of_year,year,is_weekend) VALUES ('2020-02-2...
                                                             ^

[2022-09-05 11:47:18,224] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=insert_dim_date, execution_date=20220904T000000, start_date=20220905T114717, end_date=20220905T114718
[2022-09-05 11:47:18,437] {local_task_job.py:146} INFO - Task exited with return code 1
