[2022-09-05 03:07:36,541] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task 2022-08-09T00:00:00+00:00 [queued]>
[2022-09-05 03:07:36,723] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task 2022-08-09T00:00:00+00:00 [queued]>
[2022-09-05 03:07:36,724] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:07:36,725] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2022-09-05 03:07:36,735] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:07:36,902] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-08-09T00:00:00+00:00
[2022-09-05 03:07:36,913] {standard_task_runner.py:52} INFO - Started process 289 to run task
[2022-09-05 03:07:36,951] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v2', 'second_task', '2022-08-09T00:00:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpwya4v9kk', '--error-file', '/tmp/tmpck159o0g']
[2022-09-05 03:07:36,983] {standard_task_runner.py:77} INFO - Job 38: Subtask second_task
[2022-09-05 03:07:37,215] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v2.second_task 2022-08-09T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 03:07:37,474] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v2
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-09T00:00:00+00:00
[2022-09-05 03:07:37,478] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-09-05 03:07:37,480] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2022-09-05 03:07:37,555] {bash.py:169} INFO - Output:
[2022-09-05 03:07:37,560] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2022-09-05 03:07:37,563] {bash.py:177} INFO - Command exited with return code 0
[2022-09-05 03:07:37,755] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, execution_date=20220809T000000, start_date=20220905T030736, end_date=20220905T030737
[2022-09-05 03:07:38,584] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 03:07:38,694] {local_task_job.py:146} INFO - Task exited with return code 0
