[2022-09-05 03:15:53,795] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v6.second_task 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 03:15:53,853] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v6.second_task 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 03:15:53,854] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:15:53,854] {taskinstance.py:1043} INFO - Starting attempt 1 of 3
[2022-09-05 03:15:53,855] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:15:53,895] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-09-04T00:00:00+00:00
[2022-09-05 03:15:53,900] {standard_task_runner.py:52} INFO - Started process 606 to run task
[2022-09-05 03:15:53,904] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v6', 'second_task', '2022-09-04T00:00:00+00:00', '--job-id', '117', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpbp5m53kd', '--error-file', '/tmp/tmpoal_f1mn']
[2022-09-05 03:15:53,909] {standard_task_runner.py:77} INFO - Job 117: Subtask second_task
[2022-09-05 03:15:54,019] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v6.second_task 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 03:15:54,108] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v6
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 03:15:54,109] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-09-05 03:15:54,111] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2022-09-05 03:15:54,118] {bash.py:169} INFO - Output:
[2022-09-05 03:15:54,120] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2022-09-05 03:15:54,121] {bash.py:177} INFO - Command exited with return code 0
[2022-09-05 03:15:54,215] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v6, task_id=second_task, execution_date=20220904T000000, start_date=20220905T031553, end_date=20220905T031554
[2022-09-05 03:15:54,360] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 03:15:54,400] {local_task_job.py:146} INFO - Task exited with return code 0
