[2022-09-05 03:07:50,291] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task 2022-08-24T00:00:00+00:00 [queued]>
[2022-09-05 03:07:50,546] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task 2022-08-24T00:00:00+00:00 [queued]>
[2022-09-05 03:07:50,548] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:07:50,554] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2022-09-05 03:07:50,560] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:07:50,690] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-08-24T00:00:00+00:00
[2022-09-05 03:07:50,730] {standard_task_runner.py:52} INFO - Started process 427 to run task
[2022-09-05 03:07:50,762] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v2', 'second_task', '2022-08-24T00:00:00+00:00', '--job-id', '83', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpkmxi3xus', '--error-file', '/tmp/tmpm_5uf49k']
[2022-09-05 03:07:50,792] {standard_task_runner.py:77} INFO - Job 83: Subtask second_task
[2022-09-05 03:07:51,137] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v2.second_task 2022-08-24T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 03:07:51,376] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v2
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-24T00:00:00+00:00
[2022-09-05 03:07:51,377] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-09-05 03:07:51,381] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2022-09-05 03:07:51,460] {bash.py:169} INFO - Output:
[2022-09-05 03:07:51,472] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2022-09-05 03:07:51,473] {bash.py:177} INFO - Command exited with return code 0
[2022-09-05 03:07:51,745] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, execution_date=20220824T000000, start_date=20220905T030750, end_date=20220905T030751
[2022-09-05 03:07:52,039] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 03:07:52,084] {local_task_job.py:146} INFO - Task exited with return code 0
