[2022-09-05 03:19:30,827] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v7.second_task 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 03:19:30,876] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v7.second_task 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 03:19:30,876] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:19:30,877] {taskinstance.py:1043} INFO - Starting attempt 1 of 3
[2022-09-05 03:19:30,877] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:19:30,925] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-09-04T00:00:00+00:00
[2022-09-05 03:19:30,930] {standard_task_runner.py:52} INFO - Started process 651 to run task
[2022-09-05 03:19:30,935] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v7', 'second_task', '2022-09-04T00:00:00+00:00', '--job-id', '121', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpgol6906_', '--error-file', '/tmp/tmpmte2pi2c']
[2022-09-05 03:19:30,939] {standard_task_runner.py:77} INFO - Job 121: Subtask second_task
[2022-09-05 03:19:31,043] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v7.second_task 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 03:19:31,176] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v7
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 03:19:31,178] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-09-05 03:19:31,187] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2022-09-05 03:19:31,201] {bash.py:169} INFO - Output:
[2022-09-05 03:19:31,203] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2022-09-05 03:19:31,204] {bash.py:177} INFO - Command exited with return code 0
[2022-09-05 03:19:31,415] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v7, task_id=second_task, execution_date=20220904T000000, start_date=20220905T031930, end_date=20220905T031931
[2022-09-05 03:19:31,612] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 03:19:31,630] {local_task_job.py:146} INFO - Task exited with return code 0
