[2022-09-05 03:14:26,777] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 03:14:26,821] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 03:14:26,822] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:14:26,823] {taskinstance.py:1043} INFO - Starting attempt 1 of 3
[2022-09-05 03:14:26,823] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 03:14:26,855] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-09-04T00:00:00+00:00
[2022-09-05 03:14:26,877] {standard_task_runner.py:52} INFO - Started process 582 to run task
[2022-09-05 03:14:26,883] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2022-09-04T00:00:00+00:00', '--job-id', '114', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp36npkz7e', '--error-file', '/tmp/tmpt7lkl62o']
[2022-09-05 03:14:26,886] {standard_task_runner.py:77} INFO - Job 114: Subtask second_task
[2022-09-05 03:14:26,991] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 03:14:27,088] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 03:14:27,089] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-09-05 03:14:27,090] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2022-09-05 03:14:27,097] {bash.py:169} INFO - Output:
[2022-09-05 03:14:27,099] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2022-09-05 03:14:27,100] {bash.py:177} INFO - Command exited with return code 0
[2022-09-05 03:14:27,215] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220904T000000, start_date=20220905T031426, end_date=20220905T031427
[2022-09-05 03:14:27,304] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 03:14:27,335] {local_task_job.py:146} INFO - Task exited with return code 0
